server {
    listen 80;
    server_name gapassessment.serviciosysolucionesip.com;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name gapassessment.serviciosysolucionesip.com;

    ssl_certificate     /etc/letsencrypt/live/gapassessment.serviciosysolucionesip.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/gapassessment.serviciosysolucionesip.com/privkey.pem;

    location /api/ {
        proxy_pass         http://localhost:3000;
        proxy_http_version 1.1;
        proxy_set_header   Upgrade $http_upgrade;
        proxy_set_header   Connection 'upgrade';
        proxy_set_header   Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_buffering    off;
        proxy_read_timeout 120s;
    }

    location / {
        root   /var/www/madurez-digital;
        index  index.html;
        try_files $uri $uri/ /index.html;
    }
}